version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-parameter-store: circleci/aws-parameter-store@1.0.0

filter_only_master: &filter_only_master
  filters:
    branches:
      only: master

filter_only_develop: &filter_only_develop
  filters:
    branches:
      only: develop

commands:
  upgrade-builtin-chrome:
    steps:
      - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo apt update
      - run: sudo apt --only-upgrade install google-chrome-stable
  setup-node-env:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: update libraries
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/app
    steps:
      - checkout
      - setup-node-env
      - aws-parameter-store/load:
          filter: Key=Name,Values=ryoshoku_pub_key
      - run:
          command: |
            source /tmp/parameterstore/PARAMETERSTORESOURCEFILE && \
            echo REACT_APP_PUBLIC_KEY=${ryoshoku_pub_key} > .env
      - run:
          name: build
          command: yarn build
      - run:
          name: copy artifacts
          command: mkdir /tmp/app && cp ~/app/build /tmp/app/build -r
      - persist_to_workspace:
          root: /tmp/app
          paths:
            - build
  prepare-deploy:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/app
    steps:
      - checkout
      - upgrade-builtin-chrome
      - setup-node-env
      - run:
          name: store menu.json
          command: 'curl https://ryoshoku.tk/menu.json > public/menu.json'
      - run:
          name: start application
          command: yarn start
          background: true
      - run:
          name: test before deploy
          command: yarn wait http://localhost:3000 && yarn testci
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: /tmp/app
      - run:
          name: 'menu.jsonを保存する'
          command: 'curl https://ryoshoku.tk/menu.json > /tmp/app/build/menu.json'
      - aws-s3/sync:
          from: /tmp/app/build
          to: 's3://ryoshoku.tk'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - prepare-deploy:
          <<: *filter_only_develop
          requires:
            - build
      - deploy:
          <<: *filter_only_master
          requires:
            - build