version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

filter_only_master: &filter_only_master
  filters:
    branches:
      only: master

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: setup environment
          command: yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: copy artifacts
          command: mkdir /tmp/app && cp ~/app/build /tmp/app/build -r
      - persist_to_workspace:
          root: /tmp/app
          paths:
            - build
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: /tmp/app
      - run:
          name: 'menu.jsonを保存する'
          command: 'curl http://ryoshoku.tk/menu.json > /tmp/app/build/menu.json'
      - aws-s3/sync:
          from: /tmp/app/build
          to: 's3://ryoshoku.tk'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          <<: *filter_only_master
          requires:
            - build